name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_for_aarch64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for aarch64
      run: docker build Docker --file Dockerfile --tag cmtp-responder-build:aarch64-$(date +%s)
